main:

  - name: export_type
    label: Export Type
    type: list
    options: Labeled frames,Labeled + suggested frames (recommended),Labeled + predicted + suggested frames
    default: training
    help: >
      User Labels: Only user-labeled frames
      Training: User-labeled and suggested frames
      Full: All frames including unlabeled ones

  - name: camera_category
    label: Camera Category
    type: list
    options: all
    default: all
    help: Select which camera category to export, or 'All Cameras' to export everything
